export { default as Home } from './Home'
export { default as List } from './List'
export { default as Order } from './Order'
export { default as Swipe } from './Swipe'
export { default as Tile } from './Tile'
export { default } from './Detail'
