export const button: string;
export const isDisabled: string;
export const greenTheme: string;
export const redTheme: string;
export const dockTop: string;
export const dockBottom: string;
export const dockRight: string;
export const dockLeft: string;
export const dockLeftRight: string;
