export const pageSection: string;
export const isRevealable: string;
export const isRevealed: string;
export const pageSectionTitle: string;
export const pageSectionDescription: string;
export const pageSectionContent: string;
export const dockTop: string;
export const dockBottom: string;
export const dockTopBottom: string;
