export const geoTargetItem: string;
export const location: string;
export const locationIcon: string;
export const locationName: string;
export const locationNameText: string;
export const locationCountry: string;
export const locationRadius: string;
export const removeIcon: string;
export const geoTargets: string;
