export const blockDescription: string;
export const title: string;
export const text: string;
export const icon: string;
export const content: string;
export const iconImage: string;
export const dockTop: string;
export const dockBottom: string;
export const dockTopBottom: string;
