export const appFooter: string;
export const logo: string;
export const logoImage: string;
export const company: string;
export const links: string;
export const socialNetwork: string;
export const support: string;
export const copyright: string;
export const socialNetworksGroups: string;
