export const REGISTRATION_FORM_INIT = 'REGISTRATION_FORM_INIT';
export const REGISTRATION_FORM_UPDATE_FORM_FIELD = 'REGISTRATION_FORM_UPDATE_FORM_FIELD';
export const REGISTRATION_FORM_SUBMIT = 'REGISTRATION_FORM_SUBMIT';
export const REGISTRATION_FORM_ERROR = 'REGISTRATION_FORM_ERROR';
export const REGISTRATION_FORM_PENDING = 'REGISTRATION_FORM_PENDING';
export const REGISTRATION_FORM_SUCCESS = 'REGISTRATION_FORM_SUCCESS';

export const REGISTRATION_FORM_SIGNUP_URI = '/api/merchants/v1/sign_up';
