export const languageSwitcher: string;
export const caption: string;
export const isExpanded: string;
export const icon: string;
export const label: string;
export const content: string;
export const dropdownListItems: string;
export const items: string;
export const item: string;
