export const GTM_EVENTS = {
  LANDING: {
    BANNER_CREATE_CAMPAIGN: {
      Action: 'Click',
      Category: 'Conversions',
      event: 'custom.event',
      Label: 'signup_banner',
      Name: 'Sign up',
    },
    GET_PRESENTATION: {
      Action: 'Click',
      Category: 'Interactions',
      event: 'custom.event',
      Label: 'presentation',
      Name: 'Get our presentation',
    },
    SCHEDULE_DEMO: {
      Action: 'Click',
      Category: 'Interactions',
      event: 'custom.event',
      Label: 'demo',
      Name: 'Scedule a demo',
    },
    HEADER_NAVIGATION: {
      'case-studies': {
        Action: 'Click',
        Category: 'Interactions',
        event: 'custom.event',
        Label: 'cases_header',
        Name: 'Cases',
      },
      'how-it-works': {
        Action: 'Click',
        Category: 'Interactions',
        event: 'custom.event',
        Label: 'howitworks_header',
        Name: 'How it works',
      },
      careers: {
        Action: 'Click',
        Category: 'Interactions',
        event: 'custom.event',
        Label: 'careers_header',
        Name: 'Careers',
      },
      'for-users': {
        Action: 'Click',
        Category: 'Interactions',
        event: 'custom.event',
        Label: 'users_header',
        Name: 'For users',
      },
    },
    HEADER_SIGNIN: {
      Action: 'Click',
      Category: 'Interactions',
      event: 'custom.event',
      Label: 'signin_header',
      Name: 'Sign In',
    },
    MAIN_CREATE_CAMPAIGN: {
      Action: 'Click',
      Category: 'Conversions',
      event: 'custom.event',
      Label: 'signup_main',
      Name: 'Sign up now',
    },
  },
  FOOTER_APPS: {
    'app-store': {
      Action: 'Click',
      Category: 'Interactions',
      event: 'custom.event',
      Label: 'appstore_footer',
      Name: 'Appstore Download',
    },
    'google-play': {
      Action: 'Click',
      Category: 'Interactions',
      event: 'custom.event',
      Label: 'googleplay_footer',
      Name: 'Google Play Download',
    },
  },
  FOOTER_COOKIE_POLICY_LINK: {
    Action: 'Click',
    Category: 'Interactions',
    event: 'custom.event',
    Label: 'cookiepolicy_footer',
    Name: 'Cookie Policy',
  },
  FOOTER_PRIVACY_POLICY_LINK: {
    Action: 'Click',
    Category: 'Interactions',
    event: 'custom.event',
    Label: 'privacypolicy_footer',
    Name: 'Pivacy Policy',
  },
  FOOTER_TERMS_LINK: {
    Action: 'Click',
    Category: 'Interactions',
    event: 'custom.event',
    Label: 't&c_footer',
    Name: 'Terms & Conditions',
  },
  HEADER_APPS: {
    'app-store': {
      Action: 'Click',
      Category: 'Interactions',
      event: 'custom.event',
      Label: 'appstore_header',
      Name: 'Appstore Download',
    },
    'google-play': {
      Action: 'Click',
      Category: 'Interactions',
      event: 'custom.event',
      Label: 'googleplay_header',
      Name: 'Google Play Download',
    },
  },
  LOGIN: {
    SIGN_IN: {
      Action: 'Click',
      Category: 'Interactions',
      event: 'custom.event',
      Label: 'signin_form',
      Name: 'Sign in',
    },
  },
  REGISTRATION: {
    ACCEPT_RULES: {
      Action: 'Select',
      Category: 'Interactions',
      event: 'custom.event',
      Label: 'acceptrules_form',
      Name: 'Accept Rules',
    },
    CREATE_ACCOUNT: {
      Action: 'Click',
      Category: 'Conversions',
      event: 'custom.event',
      Label: 'createacc_form',
      Name: 'Create Account',
    },
    REGISTER_SUCCESS: {
      Action: 'Sent',
      Category: 'Conversions',
      event: 'custom.event',
      Label: 'sign_up_made',
      Name: 'Register Success',
    },
    SWITCHTO_LOGIN: {
      Action: 'Click',
      Category: 'Interactions',
      event: 'custom.event',
      Label: 'alreadyacc_form',
      Name: 'Already Have account?',
    },
  },
};
