export const repoListItem: string;
export const repoListItems: string;
export const repoList: string;
export const repoListItemInfo: string;
export const repoListItemInfoSection: string;
export const repoListItemName: string;
export const repoListItemLink: string;
export const pagination: string;
export const paginationButton: string;
