export { default as DetailedInfo } from './DetailedInfo'
export { default as Footer } from './Footer'
export { default as Info } from './Info'
export { default as Main } from './Main'
export { default as Photos } from './Photos'
export { default as Wrapper } from './Wrapper'
export { default } from './Home'
