export const spendingDetailsDateColumn: string;
export const spendingDetailsIdColumn: string;
export const spendingDetailsAmountColumn: string;
export const spendingDetailsAmountHeadColumn: string;
export const spendingDetailsAmountTooltip: string;
export const spendingDetailsImpressionsColumn: string;
export const spendingDetailsPaymentMethodColumn: string;
export const spendingDetailsStatusColumn: string;
export const paymentsSpendingDetailsStubEntriesHeadCell: string;
