export const HOME_UPDATE_HOME_DETAILS = 'HOME_UPDATE_HOME_DETAILS';
export const HOME_ADD_NAVIGATION_ITEM = 'HOME_ADD_NAVIGATION_ITEM';

export const HOME_CREATIVES_CAROUSEL_PLAY_SPEED = {
  STATIC: 2 * 1000,
  VIDEO: 7 * 1000,
};
export const HOME_CREATIVES_CAROUSEL_CHANGE_SPEED = 0.5 * 1000;

export const HOMEPAGE_INFO_URI = '/api/home/v1/info';
