export const textControl: string;
export const withTooltip: string;
export const isDisabled: string;
export const static: string;
export const notEmptyValue: string;
export const input: string;
export const withIconBefore: string;
export const withIconAfter: string;
export const textControlStub: string;
