export const USER_JOIN_FORM_INIT = 'USER_JOIN_FORM_INIT';
export const USER_JOIN_FORM_PENDING = 'USER_JOIN_FORM_PENDING';
export const USER_JOIN_FORM_UPDATE_FORM_FIELD = 'USER_JOIN_FORM_UPDATE_FORM_FIELD';
export const USER_JOIN_FORM_ERROR = 'USER_JOIN_FORM_ERROR';
export const USER_JOIN_FORM_SUCCESS = 'USER_JOIN_FORM_SUCCESS';

export const USER_JOIN_INVITE_URI = '/api/join_us/1.0/users/invite';
