export const USER_LOCATION_INIT = 'USER_LOCATION_INIT';
export const USER_LOCATION_UPDATE = 'USER_LOCATION_UPDATE';
export const USER_LOCATION_UPDATE_DATA = 'USER_LOCATION_UPDATE_DATA';
export const USER_LOCATION_UPDATE_LANG = 'USER_LOCATION_UPDATE_LANG';
export const USER_LOCATION_ERROR = 'USER_LOCATION_ERROR';

export const LEGAL_INFO_URI = '/api/legal/v1/info';

export const MNFST_LEGAL_ADDRESS = 'MNFST ADVERTISING SOLUTIONS LLP, 25 Sackville street, London, W1S 3AX, UK.'
  + 'Company number OC416765';
