export const historyEntries: string;
export const historyEntriesHeadCell: string;
export const historyEntriesBodyCell: string;
export const historyEntriesRowCell: string;
export const expandableHistoryEntriesRow: string;
export const isExpanded: string;
export const historyEntriesBodyCellDetails: string;
export const historyEntryDetails: string;
export const historyEntryDetailsItem: string;
